# Generated by Django 2.1.7 on 2019-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField(help_text='Enter a article content', max_length=500)),
                ('author', models.CharField(max_length=10)),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
